pipeline{
	agent any
	stages{
		stage('stage1'){
			steps{
			sh "echo Stage1"
			}
		}
		stage('server_details'){
			steps{
			sh 'echo "Server name is : `hostname` "'
			}
		}
		stage('script_stage'){
			steps{
			sh '''
			bash ${WORKSPACE}/linux/loop_script.sh

			'''
			}
		
		}
		
}


}
